export type GemCategory = 'Sapphires' | 'Rubies' | 'Chrysoberyl' | 'Spinel' | 'Rare'

export interface Gem {
  id: string
  name: string
  species: string
  variety: string
  origin: string
  caratWeight: string
  category: GemCategory
  certification: 'GIA' | 'GRS' | 'No-Heat' | 'GIA + No-Heat' | 'GRS + No-Heat'
  colour: string      // hex for SVG fill accent
  description: string
}

export const gems: Gem[] = [
  {
    id: 'blue-sapphire-1',
    name: 'Blue Sapphire',
    species: 'Corundum',
    variety: 'Blue Sapphire',
    origin: 'Ratnapura, Sri Lanka',
    caratWeight: '3.42 ct',
    category: 'Sapphires',
    certification: 'GIA + No-Heat',
    colour: '#1a5f9e',
    description: 'A velvety cornflower-blue sapphire of exceptional clarity, unheated and certified.',
  },
  {
    id: 'padparadscha-1',
    name: 'Padparadscha Sapphire',
    species: 'Corundum',
    variety: 'Padparadscha',
    origin: 'Elahera, Sri Lanka',
    caratWeight: '2.18 ct',
    category: 'Sapphires',
    certification: 'GRS + No-Heat',
    colour: '#e8855e',
    description: 'Rare lotus-blossom hued padparadscha, the rarest of all sapphires.',
  },
  {
    id: 'pink-sapphire-1',
    name: 'Pink Sapphire',
    species: 'Corundum',
    variety: 'Pink Sapphire',
    origin: 'Ratnapura, Sri Lanka',
    caratWeight: '4.05 ct',
    category: 'Sapphires',
    certification: 'GIA + No-Heat',
    colour: '#d46b9a',
    description: 'Vivid bubblegum-pink sapphire with excellent saturation and no heat treatment.',
  },
  {
    id: 'yellow-sapphire-1',
    name: 'Yellow Sapphire',
    species: 'Corundum',
    variety: 'Yellow Sapphire',
    origin: 'Eheliyagoda, Sri Lanka',
    caratWeight: '5.67 ct',
    category: 'Sapphires',
    certification: 'GIA',
    colour: '#d4af37',
    description: 'Golden yellow sapphire with warm canary tones, ideal for Navaratna settings.',
  },
  {
    id: 'star-sapphire-1',
    name: 'Star Sapphire',
    species: 'Corundum',
    variety: 'Star Sapphire',
    origin: 'Ratnapura, Sri Lanka',
    caratWeight: '8.90 ct',
    category: 'Sapphires',
    certification: 'GRS',
    colour: '#3a6fa8',
    description: 'A mesmerising cabochon with a sharp six-rayed star phenomenon.',
  },
  {
    id: 'ruby-1',
    name: 'Ruby',
    species: 'Corundum',
    variety: 'Ruby',
    origin: 'Ratnapura, Sri Lanka',
    caratWeight: '1.85 ct',
    category: 'Rubies',
    certification: 'GRS + No-Heat',
    colour: '#c0392b',
    description: 'Pigeon-blood red ruby of Sri Lankan origin, prized for its fluorescence.',
  },
  {
    id: 'star-ruby-1',
    name: 'Star Ruby',
    species: 'Corundum',
    variety: 'Star Ruby',
    origin: 'Elahera, Sri Lanka',
    caratWeight: '6.22 ct',
    category: 'Rubies',
    certification: 'GRS',
    colour: '#a93226',
    description: 'Deep red star ruby with a vivid asterism, unheated and in original condition.',
  },
  {
    id: 'alexandrite-1',
    name: 'Alexandrite',
    species: 'Chrysoberyl',
    variety: 'Alexandrite',
    origin: 'Elahera, Sri Lanka',
    caratWeight: '1.12 ct',
    category: 'Chrysoberyl',
    certification: 'GIA + No-Heat',
    colour: '#2e8b57',
    description: 'Dramatic colour-change alexandrite: teal-green in daylight, raspberry-red under incandescent light.',
  },
  {
    id: 'cats-eye-1',
    name: "Cat's Eye",
    species: 'Chrysoberyl',
    variety: "Cat's Eye",
    origin: 'Ratnapura, Sri Lanka',
    caratWeight: '4.44 ct',
    category: 'Chrysoberyl',
    certification: 'GIA',
    colour: '#b8860b',
    description: "A honey-coloured cat's eye with a razor-sharp milk-and-honey effect.",
  },
  {
    id: 'blue-spinel-1',
    name: 'Blue Spinel',
    species: 'Spinel',
    variety: 'Blue Spinel',
    origin: 'Ratnapura, Sri Lanka',
    caratWeight: '2.77 ct',
    category: 'Spinel',
    certification: 'GIA + No-Heat',
    colour: '#2e5fa3',
    description: 'Cobalt-blue spinel with electric saturation, a collector-grade gemstone.',
  },
  {
    id: 'garnet-1',
    name: 'Hessonite Garnet',
    species: 'Garnet',
    variety: 'Hessonite',
    origin: 'Beruwala, Sri Lanka',
    caratWeight: '3.30 ct',
    category: 'Rare',
    certification: 'GIA',
    colour: '#c0712b',
    description: 'Rich cinnamon-orange hessonite, prized in Vedic astrology as Gomed.',
  },
  {
    id: 'zircon-1',
    name: 'Blue Zircon',
    species: 'Zircon',
    variety: 'Blue Zircon',
    origin: 'Ratnapura, Sri Lanka',
    caratWeight: '7.15 ct',
    category: 'Rare',
    certification: 'GIA',
    colour: '#5eb8d4',
    description: 'Sky-blue zircon with exceptional brilliance and fire, often confused with diamond.',
  },
]

export const stoneSpecies = [
  { name: 'Blue Sapphire', family: 'Corundum', colour: '#1a5f9e' },
  { name: 'Ruby', family: 'Corundum', colour: '#c0392b' },
  { name: 'Padparadscha', family: 'Corundum', colour: '#e8855e' },
  { name: 'Alexandrite', family: 'Chrysoberyl', colour: '#2e8b57' },
  { name: "Cat's Eye", family: 'Chrysoberyl', colour: '#b8860b' },
  { name: 'Blue Spinel', family: 'Spinel', colour: '#2e5fa3' },
  { name: 'Star Sapphire', family: 'Corundum', colour: '#3a6fa8' },
  { name: 'Pink Sapphire', family: 'Corundum', colour: '#d46b9a' },
  { name: 'Yellow Sapphire', family: 'Corundum', colour: '#d4af37' },
  { name: 'Garnet', family: 'Garnet', colour: '#c0712b' },
]
